IF OBJECT_ID('DIMENSIONAL..CUBOVENDAS', 'U') IS NOT NULL
	DROP TABLE DIMENSIONAL..CUBOVENDAS;

SELECT 
	CLI.CLIENTE,
	CLI.ESTADO,
	CLI.SEXO,
	CLI.STATUS,
	VENDA.QUANTIDADE,
	VENDA.VALORUNITARIO,
	VENDA.VALORTOTAL,
	VENDA.DESCONTO,
	PROD.PRODUTO,
	TEMPO.DATA,
	TEMPO.DIA,
	TEMPO.MES,
	TEMPO.ANO,
	TEMPO.TRIMESTRE,
	VENDEDOR.NOME
       
	INTO DIMENSIONAL..CUBOVENDAS
       
FROM DIMENSIONAL..DIMENSAOCLIENTE CLI
INNER JOIN DIMENSIONAL..FATOVENDAS VENDA
	ON VENDA.CHAVECLIENTE = CLI.CHAVECLIENTE
INNER JOIN DIMENSIONAL..DIMENSAOPRODUTO PROD
	ON PROD.CHAVEPRODUTO = VENDA.CHAVEPRODUTO
INNER JOIN DIMENSIONAL..DIMENSAOTEMPO TEMPO
	ON TEMPO.CHAVETEMPO = VENDA.CHAVETEMPO
INNER JOIN DIMENSIONAL..DIMENSAOVENDEDOR VENDEDOR
	ON VENDEDOR.CHAVEVENDEDOR = VENDA.CHAVEVENDEDOR

